### ISSUE TITLE
Why use GPL v3 license? not MIT?

### ISSUE THREAD

**Issue by lanistor** [vroland/epdiy#138]
Then how to use it in business production?

**Comment by vroland** [comment]
The main reason is that I wanted derivative works to stay open-source. This, for example, has helped with maintaining compatibility with the LILYGO board, that is based on epdiy. I hindsight, I probably should have chosen LGPL instead, but not having much embedded experience I didn't think of that.

**Comment by lanistor** [comment]
@vroland Thanks for your explain.
Will you change it to LGPL?

We are planing to use it in our hardware product, but we could not open source of our project code.
It's really a wonderful library, we really what to use it.

**Comment by vroland** [comment]
Since by now a number of people have contributed, I'd have to ask them all if they are Ok with re-licensing to LGPL, which is a bit cumbersome. According to Github, there are 18 contributors right now. If you are really keen and get everyone to accept (e.g. write a post here) I would be fine with changing to LGPL.

**Comment by martinberlin** [comment]
I would have no objection with a License update.

>Many of the most common free-software licenses, especially the permissive licenses, such as the original MIT/X license, BSD licenses (in the three-clause and two-clause forms, though not the original four-clause form), MPL 2.0, and LGPL, are GPL-compatible.

This will also enable my contribution to use EPDiy with LVGL possible since it is not going to be merged if this project stays with GPL v3. So now there are 17 contributors to ask. For some of them it would be maybe faster to ask in the https://epdiy.slack.com chat group.

**Comment by lanistor** [comment]
Or directly refer(@) them in this issue, or a new issue? Then waiting for their reply.

**Comment by martinberlin** [comment]
>Since by now a number of people have contributed, I'd have to ask them all if they are Ok with re-licensing to LGPL, which is a bit cumbersome.

Other contributors in order of appearance in https://github.com/vroland/epdiy/graphs/contributors
@sebastius
@mmib
@jdoubleu
@markbirss
@mcer12
@cgreening
@fdev31
@SimonSelg 
@BackSlasher
@Li-Tianming 
@holgerlembke
@entozoon 

Please give your opinion of this should be done or stays how it is. I'm fine with either decision since we need to respect all opinions and collaborations in an open source project.
Valentin if you find some time can you please give me some feedback about #131

**Comment by BackSlasher** [comment]
I don't mind.
Thanks for asking and bigger thanks for maintaining this project

**Comment by holgerlembke** [comment]
Don't mind, too (with my tiny bitsy contribution....).

**Comment by cgreening** [comment]
I've got no problem with the license change. LGPL makes it much easier for people to use.

**Comment by sebastius** [comment]
I’m okay with this!

Sebastius

**Comment by entozoon** [comment]
Definitely, the more open the better :)

**Comment by fdev31** [comment]
Same for me, +1 :)

**Comment by jdoubleu** [comment]
Thanks for asking!
I'm totally fine with `LGPL`.

**Comment by mcer12** [comment]
No problem at all with me.

**Comment by markbirss** [comment]
I'm also OK with it going more open

**Comment by Li-Tianming** [comment]
It's OK for me 🤪

**Comment by vroland** [comment]
Thanks, this is looking good so far!

I think @DavidM42 and @Sam-Izdat are missing.

**Comment by DavidM42** [comment]
Im okay with the license change too. 
I really did not change much anyways

**Comment by lanistor** [comment]
@Sam-Izdat Hi, may we get your opinion?

**Comment by martinberlin** [comment]
@mmib and @SimonSelg are the last two collaborators in my list. Do you agree to the License update?

**Comment by vroland** [comment]
I think this is complete now, since the weatcher example contributed by @mmib is under the copyright of the original author
anyway and not covered by the GPL3, and @SimonSelg contributed to hardwar production files.

**Comment by martinberlin** [comment]
Great so then it could be updated to LGPL right?
Looking forward to see if at some point my take to use EPDiy also for LVGL could be accepted. Thanks!
