### ISSUE TITLE
Really hope to support ES133TT3！

### ISSUE THREAD

**Issue by geekheart** [vroland/epdiy#190]
I saw this [news ](https://news.ycombinator.com/item?id=2624556)and became interested in the ink screen and bought ES133TT3. But there is no information, and Google searched for a long time and couldn't get any relevant information.

**Comment by martinberlin** [comment]
Hi @geekheart the link you are providing is going to a Hacker news site that has nothing to do with the epaper specs.
Please provide a link to the datasheet of this epaper so we can take a look.

**Comment by geekheart** [comment]
[ES133TT3_Ver2.0_20161011_201801119664.pdf](https://github.com/vroland/epdiy/files/9011648/ES133TT3_Ver2.0_20161011_201801119664.pdf)
Here is the only information I found

**Comment by martinberlin** [comment]
![4E9834AF-16EF-4805-B922-B891003A8D65](https://user-images.githubusercontent.com/2692928/176538927-f65a0fdc-3c14-4ff0-8494-7e4a76533cb5.png)
Sadly this won’t work since it has 16 data lines. There is simply not enough gpios in ESP32-WRover for this one, if someone would make a special version with S2 or S3 it would work, but it will take months or even years to get there.
I suggest you to check a controller that suits the display you have and to get another compatible epaper if you want to test EPDiy.
