### ISSUE TITLE
Why epaper has rendering afterimage on MODE_DU mode?

### ISSUE THREAD

**Issue by lanistor** [vroland/epdiy#210]
On MODE_GC16 mode, i can understand the afterimage, for particle indeterminate position.
But why MODE_DU mode still have afterimage? and it's serious.

I'm using `epd_hl_update_area` to call epdiy with lvgl.

**Comment by martinberlin** [comment]
LVGL usually uses a lot of small partial updates unless you configure it in a special way.
Using lots of partials sometimes leave a ghost image. It's hard to get rid of it unless you use a full refresh.
Ebook readers use a completely different controller / commercial Waveform that partly solves this making it look better. But still from time to time, they do a full refresh of the screen, since they are aware of the ghosting issue.
