### ISSUE TITLE
Support for 7.5" LilyGo DEPG0750BN screen 

### ISSUE THREAD

**Issue by karlvoigt** [vroland/epdiy#247]
I have a DEPG0750BN ( https://www.lilygo.cc/products/7-5-inch-e-paper ) screen from LillyGo as I wanted to have a slightly bigger size than the 4.7" one. I'm running it from the T5 v2.3.1 and it is supported by the EDP library and works. I want to use it with EPDIY but am a bit unsure of what changes need to be made to get it working. I hope that it'll be as easy as creating a new definition with the width and height as it is supported by EPD but I'm just unsure where to start. Any help would be appreciated.

**Comment by martinberlin** [comment]
Sorry @karlvoigt but this display is SPI and this component is about parallel displays.
You might try this one with my component CalEPD or check here in the wiki first how to set it up:

https://github.com/martinberlin/cale-idf/wiki

closing this since has actually nothing to do with this repository.
