### ISSUE TITLE
Beefed up power supply

### ISSUE THREAD

**Issue by 2dom** [vroland/epdiy#35]
Not an issue but a question ... is there a reason why you beefed up the power supply / regulators in the later version of the PCB ?. Cannot believe that the display needs that much power ?

**Comment by vroland** [comment]
You mean the double-LT1945 in the latest revision? For most displays, it's about power consumption. Boosting up to 22V, then regulating down wastes energy in battery-powered devices, since the 15V rails actually draw the most current.
Additionally, the displays draw a lot of current during refreshes, at least for a short time. With the 9.7" I haven't noticed any problems with the previous design, but with a 13.3" display I tried the display did not react as fast as it should. With the new revision, this problem went away.

**Comment by vroland** [comment]
The reasoning is also that the LT1945 is quite cheap when you source it from AliExpress, but if you don't need the lower sleep current and only use up to 9.7" displays, you will be fine with the previous revision.

**Comment by 2dom** [comment]
Thanks for the explanation...makes a lot of sense.
