### ISSUE TITLE
RV1 gives only 0.391V

### ISSUE THREAD

**Issue by kubasienki** [vroland/epdiy#39]
Hi,
I'm trying to calibrate voltage. Between VCOM pad and GND there is constant voltage of 0.391V. I haven't flashed esp yet - just plugged to usb.

**Comment by vroland** [comment]
This is because the power boosters are not enabled by default, only when the firmware enables them. So in order to calibrate VCOM, you can check out the calibration_helper example, set your display type *and revision* via menuconfig and then flash it.
When starting this firmware the serial monitor should show "VCOM enabled" and you should be able to set the voltage.

**Comment by kubasienki** [comment]
thank you
